"""empty message

Revision ID: 5e517a901608
Revises: a9437aa436bf
Create Date: 2023-04-17 12:41:51.555448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e517a901608'
down_revision = 'a9437aa436bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_consumpted', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('alg', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('info', sa.String(), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('critic_loss', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('critic_loss')
        batch_op.drop_column('actor_loss')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('info')
        batch_op.drop_column('alg')
        batch_op.drop_column('time_consumpted')

    # ### end Alembic commands ###
