"""empty message

Revision ID: a9437aa436bf
Revises: c012ff6d5be7
Create Date: 2023-04-07 12:06:58.703599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9437aa436bf'
down_revision = 'c012ff6d5be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('episode_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('num_step',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('total_reward',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('total_reward',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('num_step',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('episode_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
