"""empty message

Revision ID: c012ff6d5be7
Revises: 
Create Date: 2023-04-07 11:57:56.072625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c012ff6d5be7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_data_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_episode_training_data_id_trainning_data'), 'trainning_data', ['training_data_id'], ['id'])

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_step_episode_id_episode'), 'episode', ['episode_id'], ['episode_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_step_episode_id_episode'), type_='foreignkey')
        batch_op.drop_column('episode_id')

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_episode_training_data_id_trainning_data'), type_='foreignkey')
        batch_op.drop_column('training_data_id')

    # ### end Alembic commands ###
